### PR TITLE
Add option for manual SPI transaction control

### PR DESCRIPTION
**Pull request by d21d3q**
Fixes [this issue](https://github.com/adafruit/Ethernet2/issues/28) with Ethernet2 library. 
Arafruit doesn't seem to accept PRs so that I am moving to your repository.

### CODE REVIEW

**Comment by sstaub** [comment]
I think that PR is not a good idea, because it seems to be a problem of stm32duino. It will only confuse other users.

**Comment by d21d3q** [comment]
Not really. After finding out that issue I submitted it to stm32duino, then I started to look for way for solving it and it can't be solved in stm32duino drivers.
It is not only problem of stm32duino but probably all non-avr platforms (where setting peripherials is more complex than just writing one register). 
Why would it confuse users if default configuration is not being affected?

**Comment by d21d3q** [comment]
@sstaub ?

**Comment by sstaub** [comment]
I'm not willing to change the code for a problem of a single user. Also, that function breaks the
Arduino API. So, the problem must solved at the root. I'm generally not a friend of libraries who
makes optimizations for every controller. That is a generally a big problem of the Arduino and other platforms (like ChipKit, Teensy, Ernergia....) community and developers, who are not able to make a working simplified API. Sorry.

**Pull request closed without merging**
